# This file was generated by GoReleaser. DO NOT EDIT.
cask "agr" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "{{staged_path}}/agr"]
    end
  end

  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "8ed0de8c82b965f2b19f0fdadeb47df50ff036fbc00603fbb2854a09f0f3250b"
      url "https://github.com/k0nsta/agterm-remote/releases/download/v#{version}/agr_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fe1dca93e9b12607ac1890ec6c5763f94248b69f6a7ff06099e5b69990fef713"
      url "https://github.com/k0nsta/agterm-remote/releases/download/v#{version}/agr_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "agr"
  desc "Bridge remote agent status into agterm"
  homepage "https://github.com/k0nsta/agterm-remote"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agr"

  # No zap stanza required
end
