# This file was generated by GoReleaser. DO NOT EDIT.
cask "agr" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "{{staged_path}}/agr"]
    end
  end

  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "de6b089edbf969e1bd2f9a4f8eb07588d9385efc7a38eea6667b3623a263e4b9"
      url "https://github.com/k0nsta/agterm-remote/releases/download/v#{version}/agr_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a514273dec0abb5f49b84d2d910dbc9df572b7994307c4960ed8b8b3ab3e50b4"
      url "https://github.com/k0nsta/agterm-remote/releases/download/v#{version}/agr_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "agr"
  desc "Bridge remote agent status into agterm"
  homepage "https://github.com/k0nsta/agterm-remote"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agr"

  # No zap stanza required
end
